### ISSUE TITLE
A  error  in  bitcoinetl export_all operation

### ISSUE THREAD

**Issue by xingyushu** [blockchain-etl/bitcoin-etl#38]
environment :3.6  
python | bitcoinetl | 
3.6 |  1.3.1  |

```
[root@localhost end_block=00100199]# bitcoinetl export_all --provider-uri http:/user:pass@localhost:8332 --start 2010-01-30   --end   2013-12-30 
```
confront the error:
```
Traceback (most recent call last):
  File "/usr/local/bin/bitcoinetl", line 11, in <module>
    load_entry_point('bitcoin-etl==1.3.1', 'console_scripts', 'bitcoinetl')()
  File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/bitcoinetl/cli/export_all.py", line 102, in export_all
    output_dir, provider_uri, max_workers, export_batch_size, enrich)
  File "/usr/local/lib/python3.6/site-packages/bitcoinetl/jobs/export_all.py", line 44, in export_all
    for batch_start_block, batch_end_block, partition_dir, *args in partitions:
  File "/usr/local/lib/python3.6/site-packages/bitcoinetl/cli/export_all.py", line 60, in get_partitions
    batch_start_block, batch_end_block = btc_service.get_block_range_for_date(start_date)
  File "/usr/local/lib/python3.6/site-packages/bitcoinetl/service/btc_block_range_service.py", line 37, in get_block_range_for_date
    start_datetime = (date + timedelta(hours=start_hour, minutes=0, seconds=0)).replace(tzinfo=timezone.utc)
TypeError: 'tzinfo' is an invalid keyword argument for this function
```

what should I handle the error ?

**Comment by MCM-Mike** [comment]
Have same issue on Ubuntu 
python3.6 --version
Python 3.6.9
bitcoinetl --version
bitcoinetl, version 1.3.1
