### ISSUE TITLE
401 Client Error

### ISSUE THREAD

**Issue by etiennekintzler** [blockchain-etl/bitcoin-etl#46]
Hello :)

### Command run
I get 401 client error when running the following command : 

```bash
bitcoinetl export_blocks_and_transactions --start-block 0 --end-block 500 --provider-uri http://crypto:password@localhost:8332 --chain bitcoin --
blocks-output blocks.json --transactions-output transactions.json
```

### Config

- **OS**: Ubuntu 20.04.1 LTS
- **Python** version: Python 3.6.12
- **Bitcoinetl** version: 1.4.0

### Full stack trace

```python
2020-12-14 11:05:58,417 - ProgressLogger [INFO] - Started work. Items to process: 501.
Traceback (most recent call last):
  File "/home/crypto/.etl/lib/python3.6/site-packages/blockchainetl/executors/batch_work_executor.py", line 53, in _fail_safe_execute
    work_handler(batch)
  File "/home/crypto/.etl/lib/python3.6/site-packages/bitcoinetl/jobs/export_blocks_job.py", line 72, in _export_batch
    blocks = self.btc_service.get_blocks(block_number_batch, self.export_transactions)
  File "/home/crypto/.etl/lib/python3.6/site-packages/bitcoinetl/service/btc_service.py", line 58, in get_blocks
    block_hashes = self.get_block_hashes(block_number_batch)
  File "/home/crypto/.etl/lib/python3.6/site-packages/bitcoinetl/service/btc_service.py", line 88, in get_block_hashes
    block_hashes_response = self.bitcoin_rpc.batch(block_hash_rpc)
  File "/home/crypto/.etl/lib/python3.6/site-packages/bitcoinetl/rpc/bitcoin_rpc.py", line 45, in batch
    timeout=self.timeout
  File "/home/crypto/.etl/lib/python3.6/site-packages/bitcoinetl/rpc/request.py", line 19, in make_post_request
    response.raise_for_status()
  File "/home/crypto/.etl/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: http://crypto:password@localhost:8332/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/crypto/.etl/bin/bitcoinetl", line 8, in <module>
    sys.exit(cli())
  File "/home/crypto/.etl/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/crypto/.etl/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/crypto/.etl/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/crypto/.etl/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/crypto/.etl/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/crypto/.etl/lib/python3.6/site-packages/bitcoinetl/cli/export_blocks_and_transactions.py", line 67, in export_blocks_and_transactions
    job.run()
  File "/home/crypto/.etl/lib/python3.6/site-packages/blockchainetl/jobs/base_job.py", line 30, in run
    self._end()
  File "/home/crypto/.etl/lib/python3.6/site-packages/bitcoinetl/jobs/export_blocks_job.py", line 85, in _end
    self.batch_work_executor.shutdown()
  File "/home/crypto/.etl/lib/python3.6/site-packages/blockchainetl/executors/batch_work_executor.py", line 68, in shutdown
    self.executor.shutdown()
  File "/home/crypto/.etl/lib/python3.6/site-packages/blockchainetl/executors/fail_safe_executor.py", line 39, in shutdown
    self._check_completed_futures()
  File "/home/crypto/.etl/lib/python3.6/site-packages/blockchainetl/executors/fail_safe_executor.py", line 47, in _check_completed_futures
    future.result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/crypto/.etl/lib/python3.6/site-packages/blockchainetl/jobs/base_job.py", line 28, in run
    self._export()
  File "/home/crypto/.etl/lib/python3.6/site-packages/bitcoinetl/jobs/export_blocks_job.py", line 68, in _export
    total_items=self.end_block - self.start_block + 1
  File "/home/crypto/.etl/lib/python3.6/site-packages/blockchainetl/executors/batch_work_executor.py", line 48, in execute
    self.executor.submit(self._fail_safe_execute, work_handler, batch)
  File "/home/crypto/.etl/lib/python3.6/site-packages/blockchainetl/executors/fail_safe_executor.py", line 31, in submit
    self._check_completed_futures()
  File "/home/crypto/.etl/lib/python3.6/site-packages/blockchainetl/executors/fail_safe_executor.py", line 47, in _check_completed_futures
    future.result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/crypto/.etl/lib/python3.6/site-packages/blockchainetl/executors/batch_work_executor.py", line 64, in _fail_safe_execute
    work_handler([item])
  File "/home/crypto/.etl/lib/python3.6/site-packages/bitcoinetl/jobs/export_blocks_job.py", line 72, in _export_batch
    blocks = self.btc_service.get_blocks(block_number_batch, self.export_transactions)
  File "/home/crypto/.etl/lib/python3.6/site-packages/bitcoinetl/service/btc_service.py", line 58, in get_blocks
    block_hashes = self.get_block_hashes(block_number_batch)
  File "/home/crypto/.etl/lib/python3.6/site-packages/bitcoinetl/service/btc_service.py", line 88, in get_block_hashes
    block_hashes_response = self.bitcoin_rpc.batch(block_hash_rpc)
  File "/home/crypto/.etl/lib/python3.6/site-packages/bitcoinetl/rpc/bitcoin_rpc.py", line 45, in batch
    timeout=self.timeout
  File "/home/crypto/.etl/lib/python3.6/site-packages/bitcoinetl/rpc/request.py", line 19, in make_post_request
    response.raise_for_status()
  File "/home/crypto/.etl/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: http://crypto:password@localhost:8332/
```

### Others

I can curl the endpoint without problem. `curl localhost:8332` returns:

```bash
JSONRPC server handles only POST requests(.etl) 
```

Below is the current state of the blockchain (returned by ` bitcoin-cli -getinfo`): 
```bash
{
  "version": 200100,
  "blocks": 661319,
  "headers": 661319,
  "verificationprogress": 0.9999942484540776,
  "timeoffset": -1,
  "connections": 10,
  "proxy": "",
  "difficulty": 18670168558399.59,
  "chain": "main",
  "balance": 0.00000000,
  "keypoolsize": 1000,
  "paytxfee": 0.00000000,
  "relayfee": 0.00001000,
  "warnings": ""
}
```

**Thanks for your help !**

**Comment by etiennekintzler** [comment]
My fault, I didn't set `rpcuser` and `rpassword` in bitcoin.conf

Setting it and restarting `bitcoind` fixes the issue.
