### ISSUE TITLE
pip install bitcoin-etl error

### ISSUE THREAD

**Issue by aitianxiang** [blockchain-etl/bitcoin-etl#8]
This is the error:
$ pip install bitcoin-etl
Collecting bitcoin-etl
  Could not find a version that satisfies the requirement bitcoin-etl (from versions: )
No matching distribution found for bitcoin-etl

**Comment by medvedev1088** [comment]
It's not been published to pip yet as it's still work in progress.  Please instead check out the repo and do:

```
> pip install -e . 
> python bitcoinetl.py
```

**Comment by aitianxiang** [comment]
thank u!

**Comment by aitianxiang** [comment]
another error:
run this:
python -m bitcoinetl export_blocks_and_transactions --start-block 0 --end-block 500000 \
> --provider-uri http://atx:atx@localhost:8332 --chain bitcoin \
> --blocks-output blocks.json --transactions-output transactions.json
Traceback (most recent call last):
  File "/Users/aitianxiang/anaconda3/envs/py35/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/aitianxiang/anaconda3/envs/py35/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/aitianxiang/etl-test/bitcoin-etl/bitcoinetl/__main__.py", line 24, in <module>
    from bitcoinetl.cli import cli
  File "/Users/aitianxiang/etl-test/bitcoin-etl/bitcoinetl/cli/__init__.py", line 24, in <module>
    from bitcoinetl.cli.export_blocks_and_transactions import export_blocks_and_transactions
  File "/Users/aitianxiang/etl-test/bitcoin-etl/bitcoinetl/cli/export_blocks_and_transactions.py", line 29, in <module>
    from bitcoinetl.rpc.bitcoin_rpc import BitcoinRpc
  File "/Users/aitianxiang/etl-test/bitcoin-etl/bitcoinetl/rpc/bitcoin_rpc.py", line 26, in <module>
    from bitcoinetl.rpc.request import make_post_request
  File "/Users/aitianxiang/etl-test/bitcoin-etl/bitcoinetl/rpc/request.py", line 2, in <module>
    import lru
ModuleNotFoundError: No module named 'lru'

then i run pip install lru
this error happend:
Collecting lru
  Using cached https://files.pythonhosted.org/packages/c3/e0/1d74333975c41e22b5f83e18d9ea210dd5e9098d0c2907546be303e4f5f1/lru-0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/5t/lg6cdbcd407glzvw4lyg_5n40000gn/T/pip-install-_38xnn5m/lru/setup.py", line 2, in <module>
        from lru import __version__ as version
      File "/private/var/folders/5t/lg6cdbcd407glzvw4lyg_5n40000gn/T/pip-install-_38xnn5m/lru/lru.py", line 18
        raise KeyError, key
                      ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/5t/lg6cdbcd407glzvw4lyg_5n40000gn/T/pip-install-_38xnn5m/lru/

**Comment by medvedev1088** [comment]
What is your python version?

**Comment by aitianxiang** [comment]
Python 3.6.8 :: Anaconda custom (64-bit)

**Comment by medvedev1088** [comment]
Seems there is an issue with lru library. I removed the dependency. Please try again.

**Comment by aitianxiang** [comment]
i'll try

**Comment by aitianxiang** [comment]
thank u very much! it's a wonderful job!
